### PR TITLE
Refactored adc_dma.cpp for readability

### PR DESCRIPTION
**Pull request by hogthrob**
- replaced the lengthy adc value formulas with respective functions
  to ease reading
- removed unecessary casts for alert callbacks
- added static to the internal global variables in order to hide them from the
  other compilation units

@martinjaeger  & Co.  : please let me know if you are in general good with these kind of refactorings (extracting often used formulas etc. into relatively small functions). I learned that some prefer to see the full formulas repeated.

### CODE REVIEW

**Comment by martinjaeger** [comment]
We could integrate the functions from `adc_dma_stub.cpp` into the normal `adc_dma.cpp` so that they can access the static variables. It's maybe not ideal to mix code needed for unit-tests with code needed in actual application, but we have some dummy functions for the unit-tests in other files already anyway.

**Comment by db4ple** [comment]
I will look into this. 

Generally is the use of extern directly an not so good idea anyway as you can easily accidentally use different types for the same name. For instance we have `volatile uint16_t` in adc_dma and `uint16_t` for the same name in adc_dma_stub.c: This does not cause issues here, but that may not be the case all the time.

Given the amount of code we have to integrate, I think merging both is one of the two easiest options, the other one would be to expose adc_readings and adc_filtered using adc_dma.h

**Comment by hogthrob** [comment]
Ok, I had to add one stub function to get it done. We could also merge adc_dma_stub.h into adc_dma.h (which I did not).

**Comment by martinjaeger** [comment]
Nice, thanks. I think we can leave the stub header as it is, so I will merge it now.

**Pull request merged**
