### PR TITLE
Use methods to set/clear/query error flags part 2

### PR DESCRIPTION
**Pull request by hogthrob**

### CODE REVIEW

**Comment by hogthrob** [comment]
BTW, why don't we use powers of 2 numbers for ErrorXXX by setting the enum items with a specific number?  Now that we use methods instead of direct access, we could to this transparently. 

Benefit would be that we could use  `dev_stat.hasError(ErrorXXX |ErrorYYY)` instead of `dev_stat.hasError(ErrorXXX)  | | dev_stat.hasError(ErrorYYY)` . Same applies to clear and set operations.

This would, of course, break the C++ type checking a little.

**Comment by martinjaeger** [comment]
Yes, you're right. Would be handy. Would yo still keep an enum or use defines instead?

**Comment by hogthrob** [comment]
Yes, I'd keep the enums. I am bit of a fan of enums.

**Comment by martinjaeger** [comment]
Ok. If you want, you can add it to this PR. Otherwise I could do it on Monday.

**Pull request merged**
