### PR TITLE
Overvoltage limit overflow fix

### PR DESCRIPTION
**Pull request by hogthrob**
the bat config calculation did calculate the absolute max voltage
too high for NMC/NMC_HV, it was doing an unnecessary multiplication.
This triggered an issue in the voltage limit set code, which did not
handle the overflow of the 16bit limit value properly.

Both are fixed now. We limit the limit value to what the ADC is able
to deliver, so that we detect overvoltage for sure, even if the setting
is out of ADC range.

### CODE REVIEW

**Comment by hogthrob** [comment]
1. You are right about 0xFFF0. 
2. Your simplification was my previous solution, but I abandoned it in favor of the current one. The problem is that for very large float input values the result may exceed the uint32_t range and we would not notice this here. For that reason I switched to using float compare which handles this without problems (we get "inf" in this case).

**Comment by martinjaeger** [comment]
2. Alright, I understand. Although it's not very probable, as the user must be **very** far off the original value that is normally read by the ADC. We could even increase the range and do the shift by 4 bits as the latest step in the return statement :)

**Comment by hogthrob** [comment]
Yes, I don't think such a wrong value would happen by user interaction, more by a programming mistake or something like this. Of course, I also agree this is far fetched. But safe than sorry.

**Comment by martinjaeger** [comment]
By the way, one question: Why did you choose `const` variable here. Is it only a matter of showing that they will not be changed anymore, or does it give any speed improvements?

And could you please also add the unit-test? Otherwise I need to add it in a separate commit later on.

**Comment by hogthrob** [comment]
No speed improvements, the compiler is of course smart enough to figure out that these values are never changed. However, I started to place const if I want to express, this is a variable which should be not be changed over its lifetime. With 'const' the compiler prevents accidental breaking this rule. Of course again not necessary here.
 
I will add the unit test here now.

**Comment by martinjaeger** [comment]
> I will add the unit test here now.

Great. And do you also update the comparison in `adc_update_value`, as mentioned above? Thanks!

**Comment by martinjaeger** [comment]
> No speed improvements, the compiler is of course smart enough to figure out that these values are never changed. However, I started to place const if I want to express, this is a variable which should be not be changed over its lifetime. With 'const' the compiler prevents accidental breaking this rule. Of course again not necessary here.

Ok, thanks for the explanation. So that's a bit like in Rust, where you have to explicitly define that a variable can be changed later on, otherwise they are always constant.

**Comment by hogthrob** [comment]
Ok, done with this, can be merged.

**Comment by db4ple** [comment]
Please have a look at the last commit in this branch https://github.com/hogthrob/MPPT-Charger_Software/tree/overvoltage_fix and see if you think this is a good idea. 

I used some C++ concepts to avoid code repetition. It will not change the performance significantly (or increase/decrease code size).

**Pull request merged**
