### PR TITLE
Discharge control improvements

### PR DESCRIPTION
**Pull request by martinjaeger**
Next PR to implement improved discharging / load control, addressing also issue #59.

Please consider only last commit, all other commits are covered in previous pull request already and should disappear once that one was merged.

### CODE REVIEW

**Comment by martinjaeger** [comment]
Don't understand yet, why the last unit-test fails in the CI environment, but not on my machine. Will try to fix that.

And there is one open question: Do we see the need to control the load output based on a current limit determined by the battery? Currently, the overcurrent protection only considers the maximum the MOSFETs can handle.

Normally, the peak current capabilities of the battery should be much higher than that of the charge controller. And we can't really limit the current through the load output except for switching off. So I think it's not necessary to have an adjustable limit below the maximum current allowed by the PCB.

**Comment by martinjaeger** [comment]
I added `-Wall` to the build flags for the unit tests and found several more warnings (mostly variables that were not used). Will push an update after this PR has been merged.

**Comment by martinjaeger** [comment]
Mhh, github is still showing all commits even after most of them have been merged to master. I'll cherry-pick manually on command line and close this PR.

**Comment by hogthrob** [comment]
With the 2420-LC-0.10 I have issues with the current state introduced by or before this commit.
The PWM output do not work and consequently the DCDC transfer does not work.
 
I've started tracing the issue, just wanted to let you know my findings. On the first sight the PWM is initialized and also started as intended (I checked with the real-time debugger). But there must be something wrong, probably during system initialization.

**Comment by martinjaeger** [comment]
Ok, I only checked with the 1210 HUS. I can also check with 2420 LC on Monday.

I realized one very strange issue with the load output of the PWM 2420 LUS on Friday. It is controlled by a timer for implementation of the short circuit protection. And it didn't work at all anymore. Switching back to previous mbed version (ststm32@5.3.0) solved the problem: https://github.com/LibreSolar/charge-controller-firmware/blob/f14df2bc9d34df70401911116dadca1f3e22a6ae/platformio.ini#L24

Maybe it is the same reason. It's quite annoying, this happened to me several times already that an mbed update brakes random things in the firmware.

Didn't have the time yet to investigate what exactly broke the firmware with the mbed update.

**Comment by hogthrob** [comment]
Well, it seems I am the problem:
```
$ git bisect bad
6d56003c8cc69ade601d5f73d29b7b104159c62c is the first bad commit
commit 6d56003c8cc69ade601d5f73d29b7b104159c62c
Author: hogthrob <hogthrob@users.noreply.github.com>
Date:   Tue Oct 15 10:34:53 2019 +0200

    Unified half bridge timer handling (#53)
```
It seems I broke something when unifying things. Will have a look at it.

**Comment by hogthrob** [comment]
With my fix #66  (which fixed my own misdoings for STM32F0 based boards, not related to changes in PR #63), the software performs as expected. Of course, only a little more longer investigation will show if there isn't a glitch but so far it looks good.

**Pull request closed without merging**
